name: Automatic Pull request

# run this workflow only on new feature branches, not when they're merged to main
on:
  create:
    branches-ignore:
      - 'main'
      - 'production'
      - 'staging'

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'master'
          pr_title: 'ℹ️ Branch name: #${{ github.ref_name }}  Author:@${{ github.actor }}'
          pr_template: '.github/PULL_REQUEST_TEMPLATE/pull_request_template.md'
          pr_draft: false
          pr_label: 'in progress'
