name: Automatically create / update pull request

# run this workflow only on new feature branches, not when they're merged to main
on:
  create:
    branches-ignore:
      - 'main'
      - 'develop'

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'main'
          pr_title: 'ℹ️ ${{ github.ref_name }}  Author:@${{ github.actor }}'
          pr_template: '.github/PULL_REQUEST_TEMPLATE.md'
          pr_draft: false
